### ISSUE TITLE
20480x20480 px issue

### ISSUE THREAD

**Issue by KnudsenO** [CyprinusCarpio/MaskColorChecker#1]
Hey, thanks for your tool, very useful! I have noticed a problem. When I load a mask with the size of 20480x20480 px, I get a white preview: 

![image](https://github.com/CyprinusCarpio/MaskColorChecker/assets/122642014/0cc72898-b0ad-4c2d-82e6-e06a91b57806) 

As soon as I downscale the mask to 10240x10240 the tool works as expected. In both cases the image is a .bmp at 24 bit.

**Comment by CyprinusCarpio** [comment]
Thanks for your report.
I've tested my tool with a mask 20480x20480 in size and it worked just fine, just a bit slow.
I see that on the debug information displayed in the top left corner, the RGB values are not 255, 255, 255 which means that the image is propably loaded correctly. Do those RGB values match a color from your mask? Does the tool work other than the white preview bug, when a mask this big is used? Can it detect faulty tiles?
If so, this problem can be narrowed down to rendering.

**Comment by KnudsenO** [comment]
I can answer all your questions with yes, all other functions work fine. It seems to be a rendering problem. I have now tested the tool on another system, where the preview works without any problems.

System with faulty preview:
Win 10
Radeon RX 6700
Ryzen 7 5800X3D
32 Gig Ram

System where it works:
Win 11
RTX 4070
Ryzen 9 3900X
32 Gig Ram.

**Comment by CyprinusCarpio** [comment]
The preview is drawn in a OpenGL sub window as a single texture, therefore it's subject to the limitations of your GPU. I'm pretty sure RX 6700 has a max texture size of 16384, as is evident by [this](https://steamcommunity.com/app/322330/discussions/0/3879347492854381373/#c3878221733381342324) crash log from a game. Meanwhile even my 3060ti has double that limit, so no wonder it works just fine on your 4070.

Not a bug in my tool per se, but a problem nonetheless. I have a idea on how to fix it: detect `GL_MAX_TEXTURE_SIZE` and if the texture is bigger than that, rescale it down by a factor of 2 and then just draw it stretched in the viewport. This should handle all but the most extreme cases, cases which I couldn't test anyway because the image wouldn't even fit in my 8GB VRAM.

**Comment by CyprinusCarpio** [comment]
Should be fixed by 87bbc86 in the 0.2 release
Please test @KnudsenO

**Comment by KnudsenO** [comment]
Oh, great. Everything is now working without any problems! Thank you very much!
